// Generated by microcms-cli gen-types.
// Source: microCMS Management API (/api/v1/apis, /api/v1/apis/{endpoint}).
// Note: This command does not fetch content from microCMS Content API.
// DO NOT EDIT.

export interface MicroCMSContentId {
  id: string;
}

export interface MicroCMSDate {
  createdAt: string;
  updatedAt: string;
  publishedAt?: string;
  revisedAt?: string;
}

export interface MicroCMSImage {
  url: string;
  width?: number;
  height?: number;
  alt?: string;
}

export interface MicroCMSListResponse<T> {
  contents: (T & MicroCMSListContent)[];
  totalCount: number;
  limit: number;
  offset: number;
}

export type MicroCMSListContent = MicroCMSContentId & MicroCMSDate;
export type MicroCMSObjectContent = MicroCMSDate;

// Endpoint schema from Management API: blogs (LIST)

export type BlogsSchema = {
  title?: string;
  description?: string;
  content?: string;
};

export type BlogsContent = BlogsSchema & MicroCMSListContent;
export type BlogsListResponse = MicroCMSListResponse<BlogsSchema>;

// Endpoint schema from Management API: profile (OBJECT)

export type ProfileSchema = {
  name?: string;
  description?: string;
  area?: string;
  image?: MicroCMSImage;
  xUrl?: string;
  githubUrl?: string;
};

export type ProfileContent = ProfileSchema & MicroCMSObjectContent;

// Endpoint schema from Management API: skills (LIST)

export type SkillsSchema = {
  name?: string;
  color?: string;
};

export type SkillsContent = SkillsSchema & MicroCMSListContent;
export type SkillsListResponse = MicroCMSListResponse<SkillsSchema>;
